
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST/AUTH'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS/AUTH'
export const SIGNIN_FAIL = 'SIGNIN_FAIL/AUTH'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST/AUTH'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS/AUTH'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST/AUTH'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS/AUTH'
export const SIGNUP_FAIL = 'SIGNUP_FAIL/AUTH'

export const PROVIDER_GOOGLE = 'PROVIDER_GOOGLE/AUTH'
export const PROVIDER_FACEBOOK = 'PROVIDER_FACEBOOK/AUTH'
export const PROVIDER_TWITTER = 'PROVIDER_TWITTER/AUTH'
