
export const LOGIN_REQUEST = 'LOGIN_REQUEST/AUTH'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS/AUTH'
export const LOGIN_FAILURE = 'LOGIN_FAILURE/AUTH'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST/AUTH'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS/AUTH'

export const REGISTER_REQUEST = 'REGISTER_REQUEST/AUTH'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS/AUTH'
export const REGISTER_FAILURE = 'REGISTER_FAILURE/AUTH'

export const PROVIDER_GOOGLE = 'PROVIDER_GOOGLE/AUTH'
export const PROVIDER_FACEBOOK = 'PROVIDER_FACEBOOK/AUTH'
export const PROVIDER_TWITTER = 'PROVIDER_TWITTER/AUTH'
